id: I4C444EBA
default_language: fr
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:18.046453
last_modified: 2023-01-04 11:29:18.046471
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  AFF8:
    title: A Prayer for the Swift Rebirth of Pewar Rinpoche
    base_file: AFF8.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
